export const REPORT_TARGET_TYPES = {
  POST: "POST",
  COMMENT: "COMMENT",
  OBJECT: "OBJECT",
  OBJECT_IMPRESSION: "OBJECT_IMPRESSION",
  EVENT_CHAT_MESSAGE: "EVENT_CHAT_MESSAGE",
  TEAM_CHAT_MESSAGE: "TEAM_CHAT_MESSAGE",
} as const;

export type ReportTargetType =
  (typeof REPORT_TARGET_TYPES)[keyof typeof REPORT_TARGET_TYPES];
