-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'FOLLOWED_TEAM_EVENT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'FOLLOWED_OBJECT_EVENT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'FOLLOWED_TEAM_POST_CREATED';
ALTER TYPE "NotificationType" ADD VALUE 'FOLLOWED_OBJECT_POST_CREATED';
